'use client'
import { Inter, Outfit } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { UsermemberContext } from "./_context/UserMemberContext";
import { useState } from "react";

const inter = Outfit({ subsets: ["latin"] });

const metadata = {
  title: "Coursery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [isMember, setIsMember] = useState();
  return (
    <ClerkProvider>
      <UsermemberContext.Provider value={{ isMember, setIsMember }} >
        <html lang="en">
          <body className={inter.className}>{children}</body>
          <Toaster />
        </html>
      </UsermemberContext.Provider>
    </ClerkProvider>

  );
}
